helmDefaults:
  # time in seconds to wait for any individual Kubernetes operation
  # (like Jobs for hooks, and waits on pod/pvc/svc/deployment readiness)
  # (default 300)
  timeout: 600

repositories:
  - name: loqate
    url: https://charts.loqate.com

# chart url can be local or remote
releases:
  - name: memberlist
    namespace: loqate
    chart: "loqate/memberlist"
    version: ^0.1.0

  - name: installmanager
    namespace: loqate
    chart: "loqate/installmanager"
    version: ^0.2.0
    values:
      - image:
          repository: gbgroup/loqate-verify-install-manager
          tag: "0.1.15237"
        app:
          licenseKey: {{ requiredEnv "LICENSE_KEY" | quote }}
          products: "KBCOMMON,DSVGBR"
        storage:
          path: /run/desktop/mnt/host/c/loqate/data
        imagePullSecrets:
          - name: "installmanager"
        imageCredentials:
          username: {{ requiredEnv "DOCKER_USERNAME" | quote }}
          password: {{ requiredEnv "DOCKER_PASSWORD" | quote }}
    waitForJobs: true

  - name: spatial-api
    namespace: loqate
    chart: "loqate/spatial-api"
    version: ^0.2.0
    values:
      - image:
          repository: gbgroup/loqate-verify-spatial-api
          tag: "0.1.16684"
        storage:
          path: /run/desktop/mnt/host/c/loqate/data
        imagePullSecrets:
          - name: "spatial-api"
        imageCredentials:
          username: {{ requiredEnv "DOCKER_USERNAME" | quote }}
          password: {{ requiredEnv "DOCKER_PASSWORD" | quote }}
        app:
          libraryPath: "/lib64"
        verify:
          dataset: "row"
          healthcheckRowCountry: "gb"
    needs:
    - installmanager

  - name: querycoordinator
    namespace: loqate
    chart: "loqate/querycoordinator"
    version: ^0.2.0
    values:
      - image:
          repository: gbgroup/loqate-verify-query-coordinator
          tag: "0.1.15400"
        imagePullSecrets:
          - name: "querycoordinator"
        imageCredentials:
          username: {{ requiredEnv "DOCKER_USERNAME" | quote }}
          password: {{ requiredEnv "DOCKER_PASSWORD" | quote }}
    needs:
    - installmanager
