helmDefaults:
  # time in seconds to wait for any individual Kubernetes operation
  # (like Jobs for hooks, and waits on pod/pvc/svc/deployment readiness)
  # (default 300)
  timeout: 600

repositories:
  - name: loqate
    url: https://charts.loqate.com

# chart url can be local or remote
releases:
  - name: lqtshared
    namespace: loqate
    chart: "loqate/secret"
    version: ^0.1.0
    values:
      - nameOverride: lqtshared
        imageCredentials:
          username: {{ requiredEnv "DOCKER_USERNAME" | quote }}
          password: {{ requiredEnv "DOCKER_PASSWORD" | quote }}

  - name: memberlist
    namespace: loqate
    chart: "loqate/memberlist"
    version: ^0.1.0

  - name: spatial-api
    namespace: loqate
    chart: "loqate/spatial-api"
    version: ^0.5.3
    values:
      - verify:
          dataset: "row"
          premium: false
        storage:
          type: {{ env "LOQATE_STORAGE_TYPE" | default "local" | quote }}
          path: {{ env "LOQATE_NFS_SHARE" | default "/run/desktop/mnt/host/c/loqate/data/standard" | quote }}
          server: {{ env "LOQATE_NFS_SHARE_IP" | default "" | quote }}
          claimOverride: {{ env "CLAIM_OVERRIDE" | default "" | quote }}
        image:
          tag: {{ env "LOQATE_SPATIAL_API_VERSION" | default "latest" | quote }}
          repository: gbgroup/loqate-verify-spatial-api
        createSecret: false
        imagePullSecrets:
          - name: "lqtshared"
        podSecurityContext:
          runAsUser: {{ env "POD_USER" | default 1000 }}
          fsGroup: {{ env "POD_GROUP" | default 1000 }}
    needs:
      - lqtshared

  - name: spatial-api-premium
    namespace: loqate
    chart: "loqate/spatial-api"
    version: ^0.5.3
    values:
      - verify:
          dataset: "row"
          premium: true
        storage:
          type: {{ env "PREMIUM_LOQATE_STORAGE_TYPE" | default "local" | quote }}
          path: {{ env "PREMIUM_LOQATE_NFS_SHARE" | default "/run/desktop/mnt/host/c/loqate/data/premium" | quote }}
          server: {{ env "PREMIUM_LOQATE_NFS_SHARE_IP" | default "" | quote }}
          claimOverride: {{ env "PREMIUM_CLAIM_OVERRIDE" | default "" | quote }}
        image:
          tag: {{ env "LOQATE_SPATIAL_API_VERSION" | default "latest" | quote }}
          repository: gbgroup/loqate-verify-spatial-api
        createSecret: false
        imagePullSecrets:
          - name: "lqtshared"
        resources:
          requests:
            cpu: 2000m
            memory: 5250Mi
          limits:
            cpu: 2200m
            memory: 5775Mi
    needs:
      - lqtshared

  - name: querycoordinator
    namespace: loqate
    chart: "loqate/querycoordinator"
    version: ^0.4.0
    values:
      - image:
          tag: {{ env "LOQATE_QUERY_COORDINATOR_VERSION" | default "latest" | quote }}
          repository: gbgroup/loqate-verify-query-coordinator
        createSecret: false
        imagePullSecrets:
          - name: "lqtshared"

  # Example of Induced Delay For Debugging

  #     livenessProbe:
  #       periodSeconds: 120
  #     readinessProbe:
  #       periodSeconds: 120
    needs:
      - lqtshared
