helmDefaults:
  # time in seconds to wait for any individual Kubernetes operation
  # (like Jobs for hooks, and waits on pod/pvc/svc/deployment readiness)
  # (default 300)
  timeout: 600

repositories:
  - name: loqate
    url: https://charts.loqate.com

# chart url can be local or remote
releases:
  - name: memberlist
    namespace: loqate
    chart: "loqate/memberlist"
    version: ^0.1.0

  - name: lqtshared
    namespace: loqate
    chart: "loqate/secret"
    version: ^0.1.0
    values:
      - nameOverride: lqtshared
        imageCredentials:
          username: {{ requiredEnv "DOCKER_USERNAME" | quote }}
          password: {{ requiredEnv "DOCKER_PASSWORD" | quote }}

  - name: installmanager
    namespace: loqate
    chart: "loqate/installmanager"
    version: ^0.2.5
    values:
      - app:
          licenseKey: {{ requiredEnv "LICENSE_KEY" | quote }}
          products: {{ env "LOQATE_PRODUCTS" | default "ALL" | quote }}
        storage:
          type: {{ env "LOQATE_STORAGE_TYPE" | default "local" | quote }}
          path: {{ env "LOQATE_NFS_SHARE" | default "/run/desktop/mnt/host/c/loqate/data" | quote }}
          server: {{ env "LOQATE_NFS_SHARE_IP" | default "" | quote }}
          claimOverride: {{ env "CLAIM_OVERRIDE" | default "" | quote }}
        createSecret: false
        imagePullSecrets:
          - name: "lqtshared"
        image:
          tag: {{ env "LOQATE_INSTALLMANAGER_VERSION" | default "latest" | quote }}
          repository: gbgroup/loqate-verify-install-manager
    waitForJobs: true
    needs:
    - lqtshared

  - name: spatial-api
    namespace: loqate
    chart: "loqate/spatial-api"
    version: ^0.5.2
    values:
      - verify:
          dataset: "row"
          premium: false
        storage:
          type: {{ env "LOQATE_STORAGE_TYPE" | default "local" | quote }}
          path: {{ env "LOQATE_NFS_SHARE" | default "/run/desktop/mnt/host/c/loqate/data" | quote }}
          server: {{ env "LOQATE_NFS_SHARE_IP" | default "" | quote }}
          claimOverride: {{ env "CLAIM_OVERRIDE" | default "" | quote }}
        image:
          tag: {{ env "LOQATE_SPATIAL_API_VERSION" | default "latest" | quote }}
          repository: gbgroup/loqate-verify-spatial-api
        createSecret: false
        imagePullSecrets:
          - name: "lqtshared"
    needs:
      - installmanager
      - lqtshared

  - name: querycoordinator
    namespace: loqate
    chart: "loqate/querycoordinator"
    version: ^0.4.0
    values:
      - image:
          tag: {{ env "LOQATE_QUERY_COORDINATOR_VERSION" | default "latest" | quote }}
          repository: gbgroup/loqate-verify-query-coordinator
        createSecret: false
        imagePullSecrets:
          - name: "lqtshared"

  # Example of Induced Delay For Debugging

  #     livenessProbe:
  #       periodSeconds: 120
  #     readinessProbe:
  #       periodSeconds: 120
    needs:
      - lqtshared

  # - name: installaidata
  #   namespace: loqate
  #   chart: "loqate/installaidata"
  #   version: ^0.0.4
  #   values:
  #     - storage:
  #         type: {{ env "LOQATE_AIPARSER_STORAGE_TYPE" | default "local" | quote }}
  #         path: {{ env "LOQATE_AIPARSER_STORAGE_PATH" | default "/run/desktop/mnt/host/c/loqate/models_structured" | quote }}
  #         server: {{ env "LOQATE_AIPARSER_STORAGE_SERVER" | default "" | quote }}
  #         claimOverride: {{ env "LOQATE_AIPARSER_CLAIM_OVERRIDE" | default "" | quote }}
  #       image:
  #         tag: {{ env "LOQATE_AI_DATA_VERSION" | default "0.1.37868" | quote }}
  #         repository: gbgroup/loqate-verify-install-ai-data
  #         pullPolicy: IfNotPresent
  #       createSecret: false
  #       imagePullSecrets:
  #         - name: "lqtshared"
  #   waitForJobs: true
  #   needs:
  #   - lqtshared

  # - name: tfserve
  #   namespace: loqate
  #   chart: "loqate/tfserve"
  #   version: ^0.2.3
  #   values:
  #     - storage:
  #         type: {{ env "LOQATE_AIPARSER_STORAGE_TYPE" | default "local" | quote }}
  #         path: {{ env "LOQATE_AIPARSER_STORAGE_PATH" | default "/run/desktop/mnt/host/c/loqate/models_structured" | quote }}
  #         server: {{ env "LOQATE_AIPARSER_STORAGE_SERVER" | default "" | quote }}
  #         claimOverride: {{ env "LOQATE_AIPARSER_CLAIM_OVERRIDE" | default "" | quote }}
  #       image:
  #         tag: {{ env "LOQATE_TFSERVE_VERSION" | default "latest" | quote }}
  #         repository: gbgroup/loqate-verify-tfserve
  #       createSecret: false
  #       imagePullSecrets:
  #         - name: "lqtshared"
  #   needs:
  #     - lqtshared

  # - name: ai-parse
  #   namespace: loqate
  #   chart: "loqate/ai-parse"
  #   version: ^0.2.5
  #   values:
  #     - storage:
  #         type: {{ env "LOQATE_AIPARSER_STORAGE_TYPE" | default "local" | quote }}
  #         path: {{ env "LOQATE_AIPARSER_STORAGE_PATH" | default "/run/desktop/mnt/host/c/loqate/models_structured" | quote }}
  #         server: {{ env "LOQATE_AIPARSER_STORAGE_SERVER" | default "" | quote }}
  #         claimOverride: {{ env "LOQATE_AIPARSER_CLAIM_OVERRIDE" | default "" | quote }}
  #       image:
  #         tag: {{ env "LOQATE_AIPARSER_VERSION" | default "latest" | quote }}
  #         repository: gbgroup/loqate-verify-ai-parse-service
  #       createSecret: false
  #       imagePullSecrets:
  #         - name: "lqtshared"
  #   needs:
  #     - lqtshared
